### ISSUE TITLE
padding config

### ISSUE THREAD

**Issue by seebye** [seebye/ueberzug#3]
Yaml will be used as config format.
Padding is guessed currently, so it's error-prone.

Implementation:
```
# Options to define padding
# 1. padding in pixel
padding: 24
# 2. padding by key: read value from .Xresources
padding: internalBorder
# Maybe allow to use different paddings depending on the program name
padding:
    xterm: internalBorder
    alacritty: 24
```

**Comment by seebye** [comment]
Configs stored in `~/.config/ueberzug/{terminal_emulator_bin_name}`.
Default config will bin stored in `~/.config/ueberzug/default`, however it's not necessary till there are other settings than padding I guess.

alacritty:
```yaml
config:
    format: yaml
    path: ~/.config/alacritty/alacritty.yml

padding:
    left: window.padding.x
    top: window.padding.y
```

xterm:
```yaml
config:
    format: Xresources

padding:
    left: "*internalBorder"
    top: "*internalBorder"
```
